@extends('layouts.dashboard')

@section('title', 'Detail Tugas')

@section('dashboard-content')
<div class="d-flex justify-content-between flex-wrap align-items-center pt-3 pb-2 mb-3 border-bottom"><h1 class="h2"><i class="fas fa-clipboard-list text-orange me-2"></i>Detail Tugas #{{ str_pad($task->report_id, 5, '0', STR_PAD_LEFT) }}</h1><a href="{{ route('teknisi.tasks.index') }}" class="btn btn-secondary"><i class="fas fa-arrow-left me-1"></i> Kembali</a></div>
<div class="row"><div class="col-md-8"><div class="card border-0 mb-4"><div class="card-header bg-white"><h5 class="mb-0">Informasi Tugas</h5></div><div class="card-body"><div class="alert alert-warning"><i class="fas fa-clock me-2"></i><strong>Sisa Waktu SLA:</strong> <span id="slaRemaining"></span></div><div class="row mb-3"><div class="col-md-4"><label class="fw-bold">No. Laporan</label><p>#{{ str_pad($task->report_id, 5, '0', STR_PAD_LEFT) }}</p></div><div class="col-md-4"><label class="fw-bold">Status</label><p><x-report-status :status="$task->report->status" /></p></div><div class="col-md-4"><label class="fw-bold">Urgensi</label><p><x-urgency-badge :urgency="$task->report->urgency" /></p></div></div><div class="mb-3"><label class="fw-bold">Judul</label><p>{{ $task->report->title }}</p></div><div class="mb-3"><label class="fw-bold">Lokasi</label><p>{{ $task->report->location_detail }}</p></div><div class="mb-3"><label class="fw-bold">Deskripsi</label><p>{{ $task->report->description }}</p></div>@if($task->report->image_path)<div class="mb-3"><label class="fw-bold">Bukti Foto</label><div><img src="{{ asset('storage/'.$task->report->image_path) }}" class="img-thumbnail" style="max-width: 300px;"></div></div>@endif<hr><div class="mb-3"><label class="fw-bold">Catatan Perbaikan</label><textarea class="form-control" rows="3" placeholder="Tambahkan catatan perbaikan..." id="technicianNote"></textarea></div><div class="mb-3"><label class="fw-bold">Upload Bukti Perbaikan</label><input type="file" class="form-control" accept="image/*" multiple></div><button class="btn btn-success" onclick="completeTask()"><i class="fas fa-check-circle me-2"></i>Tandai Selesai</button></div></div></div>
<div class="col-md-4"><div class="card border-0 mb-4"><div class="card-header bg-white"><h5 class="mb-0">Informasi Pelapor</h5></div><div class="card-body text-center"><img src="{{ $task->report->user->avatar_url }}" class="rounded-circle mb-2" width="80"><h6>{{ $task->report->user->name }}</h6><p class="text-muted small">{{ $task->report->user->role }}</p><hr><p><i class="fas fa-envelope me-2 text-orange"></i> {{ $task->report->user->email }}</p><p><i class="fas fa-phone me-2 text-orange"></i> {{ $task->report->user->phone ?? '-' }}</p></div></div><div class="card border-0"><div class="card-header bg-white"><h5 class="mb-0">Timeline</h5></div><div class="card-body"><x-timeline :items="[['status'=>'completed','title'=>'Laporan Dibuat','date'=>$task->report->created_at->format('d M Y, H:i'),'user'=>$task->report->user->name],['status'=>'active','title'=>'Ditugaskan ke Teknisi','date'=>$task->assigned_at->format('d M Y, H:i'),'user'=>'Admin'],['status'=>'pending','title'=>'Dalam Pengerjaan','description'=>'Proses perbaikan sedang berlangsung']]" /></div></div></div></div>
@endsection

@push('scripts')
<script>
function updateSLATimer(){const deadline=new Date('{{ $task->report->sla_deadline }}');const now=new Date();const diff=deadline-now;if(diff<=0){document.getElementById('slaRemaining').innerHTML='00:00:00';return;}const hours=Math.floor(diff/(1000*60*60));const minutes=Math.floor((diff%(1000*60*60))/(1000*60));const seconds=Math.floor((diff%(1000*60))/1000);document.getElementById('slaRemaining').innerHTML=String(hours).padStart(2,'0')+':'+String(minutes).padStart(2,'0')+':'+String(seconds).padStart(2,'0');}
updateSLATimer();setInterval(updateSLATimer,1000);
function completeTask(){Swal.fire({title:'Selesaikan Tugas?',text:'Apakah Anda yakin tugas ini sudah selesai?',icon:'question',showCancelButton:true,confirmButtonColor:'#28a745',cancelButtonColor:'#6c757d',confirmButtonText:'Ya, Selesai!'}).then((result)=>{if(result.isConfirmed){Swal.fire('Berhasil!','Tugas telah ditandai selesai','success');}});}
</script>
@endpush