services:
  db:
    image: mariadb:lts-noble
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: laravel
      MARIADB_ROOT_PASSWORD: password
      MARIADB_PORT: 3306
    networks:
      - laravel

  app:
    image: ghcr.io/p8328720-droid/software-engineering:latest
    ports:
      - "8000:80"
    environment:
      - LOG_CHANNEL=stack
      - LOG_LEVEL=debug
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - CACHE_STORE=redis
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=redis
    depends_on:
      - db
    networks:
      - laravel

  redis:
    image: redis:alpine
    networks:
      - laravel

networks:
  laravel:
    driver: bridge