services:
  db:
    image: mariadb:lts-noble
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_DATABASE: laravel
      MARIADB_ROOT_PASSWORD: password
      MARIADB_PORT: 3306
    networks:
      - laravel

  app:
    image: ghcr.io/p8328720-droid/software-engineering:latest
    environment:
      - APP_ENV=PRODUCTION
      - DB_CONNECTION=mariadb
      - DB_HOST=db
      - DB_DATABASE=laravel
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - SESSION_DRIVER=redis
      - QUEUE_CONNECTION=redis
      - CACHE_STORE=redis
      - REDIS_CLIENT=phpredis
      - REDIS_HOST=redis
    depends_on:
      - db
    volumes:
      - asset_data:/var/www/app/public
      - storage_data:/var/www/app/storage
    networks:
      - laravel

  web:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      - asset_data:/var/www/app/public:ro
      - storage_data:/var/www/app/storage
    depends_on:
      - app
    networks:
      - laravel

  redis:
    image: redis:alpine
    networks:
      - laravel

volumes:
  asset_data:
  storage_data:
networks:
  laravel:
    driver: bridge