@extends('layouts.admin')

@section('title', 'Admin Dashboard')

@section('admin-content')
<div class="d-flex justify-content-between flex-wrap align-items-center pt-3 pb-2 mb-4 border-bottom"><h1 class="h2"><i class="fas fa-tachometer-alt me-2 text-orange"></i>Dashboard Admin</h1><div><span class="text-muted">{{ now()->format('d F Y') }}</span></div></div>

<div class="row mb-4"><div class="col-md-3 mb-3"><div class="card stat-card border-0"><div class="card-body"><div class="d-flex justify-content-between"><div><p class="text-muted">Total Laporan</p><h2 class="text-orange">{{ number_format($stats['total_reports'] ?? 0) }}</h2></div><div><i class="fas fa-flag-checkered fa-3x text-orange-light"></i></div></div></div></div></div>
<div class="col-md-3 mb-3"><div class="card stat-card border-0"><div class="card-body"><div class="d-flex justify-content-between"><div><p class="text-muted">Pending</p><h2 class="text-warning">{{ number_format($stats['pending_reports'] ?? 0) }}</h2></div><div><i class="fas fa-clock fa-3x text-warning"></i></div></div></div></div></div>
<div class="col-md-3 mb-3"><div class="card stat-card border-0"><div class="card-body"><div class="d-flex justify-content-between"><div><p class="text-muted">Diproses</p><h2 class="text-info">{{ number_format($stats['in_progress_reports'] ?? 0) }}</h2></div><div><i class="fas fa-spinner fa-3x text-info"></i></div></div></div></div></div>
<div class="col-md-3 mb-3"><div class="card stat-card border-0"><div class="card-body"><div class="d-flex justify-content-between"><div><p class="text-muted">Selesai</p><h2 class="text-success">{{ number_format($stats['completed_reports'] ?? 0) }}</h2></div><div><i class="fas fa-check-circle fa-3x text-success"></i></div></div></div></div></div></div>

<div class="row mb-4"><div class="col-md-3 mb-3"><div class="card stat-card border-0"><div class="card-body"><div class="d-flex justify-content-between"><div><p class="text-muted">Total User</p><h2 class="text-primary">{{ number_format($stats['total_users'] ?? 0) }}</h2></div><div><i class="fas fa-users fa-3x text-primary"></i></div></div><small class="text-muted">Mahasiswa: {{ number_format($stats['total_students'] ?? 0) }} | Teknisi: {{ number_format($stats['total_technicians'] ?? 0) }}</small></div></div></div>
<div class="col-md-3 mb-3"><div class="card stat-card border-0"><div class="card-body"><div class="d-flex justify-content-between"><div><p class="text-muted">Total Fasilitas</p><h2 class="text-success">{{ number_format($stats['total_facilities'] ?? 0) }}</h2></div><div><i class="fas fa-building fa-3x text-success"></i></div></div></div></div></div>
<div class="col-md-3 mb-3"><div class="card stat-card border-0"><div class="card-body"><div class="d-flex justify-content-between"><div><p class="text-muted">SLA Violation</p><h2 class="text-danger">{{ number_format($stats['sla_violations'] ?? 0) }}</h2></div><div><i class="fas fa-exclamation-triangle fa-3x text-danger"></i></div></div></div></div></div>
<div class="col-md-3 mb-3"><div class="card stat-card border-0"><div class="card-body"><div class="d-flex justify-content-between"><div><p class="text-muted">Kepatuhan SLA</p>@php $compliance = isset($stats['total_reports']) && $stats['total_reports'] > 0 ? round((($stats['total_reports'] - ($stats['sla_violations'] ?? 0)) / $stats['total_reports']) * 100) : 100; @endphp<h2 class="text-info">{{ $compliance }}<small>%</small></h2></div><div><i class="fas fa-chart-line fa-3x text-info"></i></div></div></div></div></div></div>

<div class="row mb-4"><div class="col-12"><div class="card border-0"><div class="card-header bg-white d-flex justify-content-between"><h5 class="mb-0"><i class="fas fa-list-alt text-orange me-2"></i>Laporan Terbaru</h5><a href="#" class="btn btn-sm btn-outline-primary">Lihat Semua</a></div><div class="card-body"><div class="table-responsive"><table class="table table-hover"><thead><tr class="table-light"><th>ID</th><th>Pelapor</th><th>Fasilitas</th><th>Judul</th><th>Status</th><th>Tanggal</th><th>Aksi</th></tr></thead><tbody>@forelse($recent_reports as $report)<tr><td>#{{ str_pad($report->id, 5, '0', STR_PAD_LEFT) }}</td><td>{{ $report->user->name }}</td><td>{{ $report->facility->name }}</td><td>{{ Str::limit($report->title, 30) }}</td><td>{!! $report->status_badge !!}</td><td>{{ $report->created_at->format('d/m/Y H:i') }}</td><td><a href="#" class="btn btn-sm btn-outline-primary"><i class="fas fa-eye"></i></a></td></tr>@empty<tr><td colspan="7" class="text-center py-4"><i class="fas fa-inbox fa-3x text-muted mb-2 d-block"></i>Belum ada laporan</td></tr>@endforelse</tbody></table></div></div></div></div></div>

<div class="row"><div class="col-12"><div class="card border-0"><div class="card-header bg-white d-flex justify-content-between"><h5 class="mb-0"><i class="fas fa-users text-orange me-2"></i>User Terbaru</h5><a href="{{ route('admin.users') }}" class="btn btn-sm btn-outline-primary">Kelola User</a></div><div class="card-body"><div class="table-responsive"><table class="table table-hover"><thead><tr class="table-light"><th>Nama</th><th>Email</th><th>NIM</th><th>Role</th><th>Tanggal Daftar</th><th>Aksi</th></tr></thead><tbody>@forelse($recent_users as $user)<tr><td>{{ $user->name }}</td><td>{{ $user->email }}</td><td>{{ $user->student_id ?? '-' }}</td><td>@if($user->role == 'admin')<span class="badge bg-danger">Admin</span>@elseif($user->role == 'teknisi')<span class="badge bg-info">Teknisi</span>@else<span class="badge bg-success">Mahasiswa</span>@endif</td><td>{{ $user->created_at->format('d/m/Y') }}</td><td><a href="{{ route('admin.users.edit', $user->id) }}" class="btn btn-sm btn-outline-primary"><i class="fas fa-edit"></i></a></td></tr>@empty<tr><td colspan="6" class="text-center py-4">Belum ada user</td></tr>@endforelse</tbody></table></div></div></div></div></div>
@endsection

@push('styles')
<style>.stat-card{transition:transform .3s;border-radius:15px}.stat-card:hover{transform:translateY(-5px)}.text-orange{color:#FF6B35}.text-orange-light{color:#FF8C42}</style>
@endpush