server {
    listen 80;
    root /var/www/app/public;
    index index.php;

    client_max_body_size 128m;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        
        # Dialirkan ke localhost karena php-fpm berjalan di container yang sama
        fastcgi_pass 127.0.0.1:9000;
        
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    location ~ /\.(?!well-known).* {
        deny all;
    }
}