server {
    listen 80;
    root /var/www/public;
    index index.php;

    # client_max_body_size 128m;

    charset utf-8;

    # Logging (Optional but recommended)
    # access_log /var/log/nginx/app_access.log;
    # error_log  /var/log/nginx/app_error.log error;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        
        # FIXED: Combined using a semicolon instead of \n
        # fastcgi_param PHP_VALUE "upload_max_filesize=128M; post_max_size=128M";
        
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Block access to hidden files (.env, .git, etc.) except .well-known
    location ~ /\.(?!well-known).* {
        deny all;
    }
}