server {
    listen 80;
    # CHANGED: Updated directory to /var/www/app/public
    root /var/www/app/public;
    index index.php;

    # FIX: Allows Nginx to accept larger file payloads
    client_max_body_size 128m;

    charset utf-8;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass app:9000;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }

    # Block access to hidden files (.env, .git, etc.) except .well-known
    location ~ /\.(?!well-known).* {
        deny all;
    }
}