@extends('layouts.dashboard')

@section('title', 'Detail Laporan')

@section('dashboard-content')
<div class="row">
    <div class="col-md-8"><div class="card border-0"><div class="card-header bg-white"><h5 class="mb-0">Detail Laporan #{{ str_pad($report->id, 5, '0', STR_PAD_LEFT) }}</h5></div><div class="card-body"><div class="row mb-3"><div class="col-md-6"><label class="fw-bold">Judul</label><p>{{ $report->title }}</p></div><div class="col-md-6"><label class="fw-bold">Fasilitas</label><p>{{ $report->facility->name }} - {{ $report->facility->location }}</p></div></div><div class="row mb-3"><div class="col-md-6"><label class="fw-bold">Lokasi Detail</label><p>{{ $report->location_detail }}</p></div><div class="col-md-6"><label class="fw-bold">Tingkat Urgensi</label><p><x-urgency-badge :urgency="$report->urgency" /></p></div></div><div class="mb-3"><label class="fw-bold">Deskripsi</label><p>{{ $report->description }}</p></div>@if($report->image_path)<div class="mb-3"><label class="fw-bold">Bukti Foto</label><div><img src="{{ asset('storage/'.$report->image_path) }}" class="img-thumbnail" style="max-width: 300px;"></div></div>@endif</div></div></div>
    <div class="col-md-4"><div class="card border-0 mb-3"><div class="card-header bg-white"><h5 class="mb-0">Status Laporan</h5></div><div class="card-body text-center"><div class="mb-3"><i class="fas fa-{{ $report->status == 'pending' ? 'clock' : ($report->status == 'in_progress' ? 'spinner fa-spin' : 'check-circle') }} fa-3x text-{{ $report->status == 'pending' ? 'secondary' : ($report->status == 'in_progress' ? 'warning' : 'success') }}"></i><h3 class="mt-2">{{ $report->status == 'pending' ? 'Menunggu' : ($report->status == 'in_progress' ? 'Diproses' : 'Selesai') }}</h3></div><hr><div class="text-start"><p><i class="fas fa-calendar me-2"></i> Dilaporkan: {{ $report->created_at->format('d M Y, H:i') }}</p><p><i class="fas fa-hourglass-half me-2"></i> SLA Deadline: {{ $report->sla_deadline->format('d M Y, H:i') }}</p></div></div></div><div class="card border-0"><div class="card-header bg-white"><h5 class="mb-0">Timeline</h5></div><div class="card-body"><x-timeline :items="$report->statusHistory->map(function($history){ return ['status' => $history->status == 'completed' ? 'completed' : ($history->status == 'in_progress' ? 'active' : 'pending'), 'title' => ucfirst($history->status), 'date' => $history->created_at->format('d M Y, H:i'), 'description' => $history->description]; })->toArray()" /></div></div></div>
</div>
@endsection